baseURL = "https://example.com"
languageCode = "en-us"
title = "A Working Diary"

[taxonomies]
  tag = "tags"

[permalinks]
  posts = "/blog/:title/"


# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Journal"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[params]
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "This is a working journal of how I handled various situations in the workplace and what I learned from the experiences."
